FROM ubuntu:22.04@sha256:962f6cadeae0ea6284001009daa4cc9a8c37e75d1f5191cf0eb83fe565b63dd7
RUN curl -fsSo /tmp/go.tar.gz https://go.dev/dl/go1.22.0.linux-amd64.tar.gz && tar -xzf /tmp/go.tar.gz -C /usr/local
