# yaml-language-server: $schema=https://schemas.rtinternal.net/schema/actionlint.json
---
self-hosted-runner:
  # Pending https://github.com/rhysd/actionlint/issues/533
  labels: ['windows-11-arm']
# Configuration variables in array of strings defined in your repository or
# organization. `null` means disabling configuration variables check.
# Empty array means no configuration variable is allowed.
config-variables:
  - UV_FROZEN
  - UV_NO_EDITABLE
  - CARGO_TERM_COLOR
  - CLICOLOR
# Configuration for file paths. The keys are glob patterns to match to file
# paths relative to the repository root. The values are the configurations for
# the file paths. Note that the path separator is always '/'.
# The following configurations are available.
#
# "ignore" is an array of regular expression patterns. Matched error messages
# are ignored. This is similar to the "-ignore" command line option.
paths:
  .github/workflows/**/*.{yml,yaml}:
    ignore:
      - 'shellcheck reported issue in this script: SC2086:.+'
      - 'shellcheck reported issue in this script: SC2028:.+'
      - 'shellcheck reported issue in this script: SC2162:.+'
