# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: 'en-US'
early_access: true
reviews:
  profile: 'assertive'
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: true
  auto_review:
    enabled: true
    drafts: false
    labels:
      - '!autorelease: tagged'  # release-please
  tools:
    ast-grep:
      rule_dirs:
        - ".sg/rules"
      util_dirs:
        - ".sg/utils"
    golangci-lint:
      enabled: true
    shellcheck:
      enabled: true
    hadolint:
      enabled: false
    ruff:
      enabled: false
    markdownlint:
      enabled: false
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: true
    biome:
      enabled: false
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    eslint:
      enabled: false
    actionlint:
      enabled: true
  path_instructions:
    - path: "**/*.go"
      instructions: |
        This project targets Go 1.25.6 (see go.mod)
        When reviewing Go code, insist on usage of newest, modern Go features, not older versions.

    - path: '**/internal/integration/testdata/**'
      instructions: |
        These are test fixture files that contain intentional code patterns for testing purposes.
        Do not provide any review comments, suggestions, or analysis.
        Do not flag any issues or violations.
        Simply acknowledge these are test fixtures and skip detailed review.
  path_filters:
    - '!**/internal/integration/testdata/**'
    - '!CHANGELOG.md'
chat:
  auto_reply: true
knowledge_base:
  learnings:
    scope: local
  web_search:
    enabled: true
