# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
---
version: '2'
run:
  concurrency: 4
  go: "1.25.6"
  modules-download-mode: readonly
  timeout: 5m
linters:
  default: all
  enable:
    - customlint # Custom tally-specific rules
  disable:
    - dupword # duplicate words - too noisy
    - err113 # dynamic errors - too strict for CLI tool
    - exhaustruct # requires all struct fields - too strict
    - gochecknoglobals # global vars - CLI requires them
    - gochecknoinits # init functions - CLI requires them
    - godoclint # doc lint - too strict
    - godot # dots at end of comments - too strict
    - ireturn # return interfaces - too strict for this codebase
    - mnd # magic numbers - too noisy
    - nlreturn # newlines before returns - too opinionated
    - noctx # context in http - not applicable
    - noinlineerr # inline errors - too strict
    - tagliatelle # struct tag naming - not needed
    - testpackage # separate test packages - not needed
    - varnamelen # variable name length - too strict
    - wastedassign # wasted assignments - too noisy
    - wrapcheck # wrap all errors - too strict for internal packages
    - wsl # whitespace linter - too strict
    - wsl_v5 # whitespace linter v5 - too strict
  settings:
    gocognit:
      # Minimal code complexity to report.
      # Default: 30
      min-complexity: 43
    cyclop:
      max-complexity: 26
    nestif:
      min-complexity: 13
    custom:
      customlint:
        type: module
    depguard:
      rules:
        main:
          deny:
            - pkg: 'encoding/json$'
              desc: 'Use stdlib v2 package "encoding/json/v2" instead.'
            - pkg: 'github.com/go-json-experiment/json$'
              desc: 'Use stdlib v2 package "encoding/json/v2" instead.'
            - pkg: 'github.com/go-json-experiment/json/v1$'
              desc: 'Use stdlib v2 package "encoding/json/v2" instead.'
    forbidigo:
      analyze-types: true
      forbid:
        # Enforce buildkit usage for Dockerfile parsing (per CLAUDE.md philosophy)
        - pattern: '.*'
          msg: 'Use moby/buildkit/frontend/dockerfile/parser instead of docker/docker parser'
          pkg: '^github\.com/docker/docker/builder/dockerfile/parser$'
        # Enforce buildkit instruction types
        - pattern: '.*'
          msg: 'Use moby/buildkit/frontend/dockerfile/instructions instead'
          pkg: '^github\.com/docker/docker/builder/dockerfile/instructions$'
        # Prevent docker/docker API types
        - pattern: '.*'
          msg: 'Use moby/buildkit types or OCI image-spec types instead'
          pkg: '^github\.com/docker/docker/api/types$'
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
    funlen:
      lines: 500
      statements: 50
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - whyNoLint
        - hugeParam
        - rangeValCopy
        - unnamedResult # conflicts with nonamedreturns linter
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 25
    govet:
      disable:
        - fieldalignment
        - shadow # too strict for idiomatic Go err handling patterns
      enable-all: true
    lll:
      line-length: 140
    revive:
      rules:
        - name: unused-parameter
          disabled: true
    staticcheck:
      checks: ["all"]
  exclusions:
    presets:
      - comments
      - std-error-handling
    rules:
      - linters:
          - revive
        text: "unused-parameter:"
      # gosec: allow file operations with variables in CLI tool
      - linters:
          - gosec
        text: "G304"
      - linters:
          - maintidx
          - mnd
        path: ".*_test\\.go"
      # gosec: allow subprocess with variables in tests and CLI
      - linters:
          - gosec
        text: "G204"
        path: ".*_test\\.go"
      - linters:
          - gosec
        text: "G204"
        path: "internal/integration/"
      # gosec: allow 0644 permissions in tests
      - linters:
          - gosec
        text: "G306"
        path: ".*_test\\.go"
      # paralleltest/tparallel: subtests share tmpDir with file create/remove
      - linters:
          - paralleltest
          - tparallel
        path: "internal/config/config_test\\.go"
        text: "TestDiscover|TestLoad"
      # paralleltest: tests mutate global resolver registry
      - linters:
          - paralleltest
        path: "internal/fix/(resolver|fixer)_test\\.go"
        text: "TestResolverRegistry|TestRegisterResolver_Duplicate|TestFixer_Apply_AsyncFix|TestFixer_Apply_DefaultConcurrency"
      # dupl: allow duplicate code in tests (table-driven test patterns)
      - linters:
          - dupl
        path: ".*_test\\.go"
      # goconst: allow repeated strings in tests (expected values)
      - linters:
          - goconst
        path: ".*_test\\.go"
      # errcheck: allow unchecked Write in test http handlers
      - linters:
          - errcheck
        text: "w\\.Write"
        path: ".*_test\\.go"
      - linters:
          - errcheck
        text: "w\\.Write"
        path: "internal/testutil/"
      # errcheck: allow blank assignment for close in defers (error not actionable)
      - linters:
          - errcheck
        text: "Error return value is not checked"
        source: "defer func\\(\\) \\{ _ ="
      # depguard: keep stdlib encoding/json only at the jsonrpc2 interop boundary.
      - linters:
          - depguard
        path: "internal/lspserver/server\\.go"
formatters:
  enable:
    - golines
  settings:
    golines:
      max-len: 140
      tab-len: 4
      reformat-tags: true
      chain-split-dots: true
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
