# Codecov configuration
# https://docs.codecov.com/docs/codecovyml-reference
# yaml-language-server: $schema=https://json.schemastore.org/codecov.json
---
codecov:
  notify:
    # Wait for both `CI` and `VS Code Smoke` workflow uploads before posting a PR comment.
    after_n_builds: 2
    wait_for_ci: true
coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 2%
    patch:
      default:
        target: 80%
ignore:
  - "**/internal/testutil/**"
  - "**/internal/integration/testdata/**"
  # Generated LSP protocol types.
  - "internal/lsp/protocol/lsp_generated.go"
  - "github.com/wharflab/tally/internal/lsp/protocol/lsp_generated.go"
  - "*_generated.go"
  - "scripts/**"
  # Go coverage profiles can use module-prefixed paths.
  - "github.com/wharflab/tally/internal/lsp/protocol/*_generated.go"
  - "github.com/wharflab/tally/scripts/**"
# Test analytics configuration
# https://docs.codecov.com/docs/test-analytics
test_analytics:
  enabled: true
# Comment configuration
comment:
  behavior: default
  require_changes: false
  require_base: true
  require_head: true
  show_critical_paths: true
  # Test results in PR comments
  show_test_results: true
# Parsers configuration
parsers:
  junit:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false
# GitHub integration
github_checks:
  annotations: true
# Status checks configuration
status_checks:
  default_rules:
    flag_coverage_not_uploaded_behavior: include
