// Code generated by _tools/schema-gen. DO NOT EDIT.

package schemas

const RootConfigSchemaID = "https://schemas.tally.dev/root/tally-config.schema.json"

var ruleSchemaIDs = map[string]string{
	"hadolint/DL3001":                    "https://schemas.tally.dev/rules/hadolint/dl3001.schema.json",
	"hadolint/DL3026":                    "https://schemas.tally.dev/rules/hadolint/dl3026.schema.json",
	"tally/consistent-indentation":       "https://schemas.tally.dev/rules/tally/consistent-indentation.schema.json",
	"tally/max-lines":                    "https://schemas.tally.dev/rules/tally/max-lines.schema.json",
	"tally/newline-between-instructions": "https://schemas.tally.dev/rules/tally/newline-between-instructions.schema.json",
	"tally/newline-per-chained-call":     "https://schemas.tally.dev/rules/tally/newline-per-chained-call.schema.json",
	"tally/no-trailing-spaces":           "https://schemas.tally.dev/rules/tally/no-trailing-spaces.schema.json",
	"tally/prefer-add-unpack":            "https://schemas.tally.dev/rules/tally/prefer-add-unpack.schema.json",
	"tally/prefer-copy-heredoc":          "https://schemas.tally.dev/rules/tally/prefer-copy-heredoc.schema.json",
	"tally/prefer-multi-stage-build":     "https://schemas.tally.dev/rules/tally/prefer-multi-stage-build.schema.json",
	"tally/prefer-run-heredoc":           "https://schemas.tally.dev/rules/tally/prefer-run-heredoc.schema.json",
}

var schemaBytesByID = map[string][]byte{
	"https://schemas.tally.dev/root/tally-config.schema.json": []byte(`
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.tally.dev/root/tally-config.schema.json",
  "title": "tally configuration",
  "description": "Configuration schema for tally Dockerfile linter",
  "type": "object",
  "properties": {
    "rules": {
      "type": "object",
      "properties": {
        "include": {
          "type": "array",
          "items": { "type": "string" }
        },
        "exclude": {
          "type": "array",
          "items": { "type": "string" }
        },
        "tally": {
          "$ref": "../../rules/tally/index.schema.json"
        },
        "hadolint": {
          "$ref": "../../rules/hadolint/index.schema.json"
        },
        "buildkit": {
          "$ref": "../../rules/buildkit/index.schema.json"
        }
      },
      "additionalProperties": false
    },
    "output": {
      "type": "object",
      "properties": {
        "format": {
          "type": "string",
          "enum": ["text", "json", "sarif", "github-actions", "markdown"],
          "default": "text"
        },
        "path": {
          "type": "string",
          "default": "stdout"
        },
        "show-source": {
          "type": "boolean",
          "default": true
        },
        "fail-level": {
          "type": "string",
          "enum": ["error", "warning", "info", "style", "none"],
          "default": "style"
        }
      },
      "additionalProperties": false
    },
    "inline-directives": {
      "type": "object",
      "properties": {
        "enabled": {
          "type": "boolean",
          "default": true
        },
        "warn-unused": {
          "type": "boolean",
          "default": false
        },
        "validate-rules": {
          "type": "boolean",
          "default": false
        },
        "require-reason": {
          "type": "boolean",
          "default": false
        }
      },
      "additionalProperties": false
    },
    "ai": {
      "type": "object",
      "properties": {
        "enabled": {
          "type": "boolean",
          "default": false
        },
        "command": {
          "type": "array",
          "items": { "type": "string" }
        },
        "timeout": {
          "type": "string",
          "default": "90s"
        },
        "max-input-bytes": {
          "type": "integer",
          "default": 262144,
          "minimum": 0
        },
        "redact-secrets": {
          "type": "boolean",
          "default": true
        }
      },
      "additionalProperties": false
    },
    "slow-checks": {
      "type": "object",
      "properties": {
        "mode": {
          "type": "string",
          "enum": ["auto", "on", "off"],
          "default": "auto"
        },
        "fail-fast": {
          "type": "boolean",
          "default": true
        },
        "timeout": {
          "type": "string",
          "default": "20s"
        }
      },
      "additionalProperties": false
    }
  },
  "additionalProperties": false
}
`),
	"https://schemas.tally.dev/rules/buildkit/index.schema.json": []byte(`
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.tally.dev/rules/buildkit/index.schema.json",
  "$comment": "Code generated by _tools/schema-gen. DO NOT EDIT.",
  "title": "buildkit/* rule namespace config",
  "description": "Schema for rules.buildkit configuration; keys are rule names within the buildkit namespace.",
  "type": "object",
  "additionalProperties": {
    "$ref": "../rule-config.schema.json#/$defs/genericRuleConfig"
  },
  "examples": [
    {
      "StageNameCasing": {
        "severity": "warning"
      }
    }
  ]
}
`),
	"https://schemas.tally.dev/rules/hadolint/dl3001.schema.json": []byte(`
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.tally.dev/rules/hadolint/dl3001.schema.json",
  "title": "hadolint/DL3001 rule config",
  "description": "Configuration options for the hadolint/DL3001 rule.",
  "type": "object",
  "properties": {
    "severity": { "$ref": "../rule-config.schema.json#/$defs/severity" },
    "fix": { "$ref": "../rule-config.schema.json#/$defs/fix" },
    "exclude": { "$ref": "../rule-config.schema.json#/$defs/exclude" },
    "invalid-commands": {
      "type": "array",
      "description": "Commands to flag as invalid inside a container.",
      "items": {
        "type": "string",
        "minLength": 1
      },
      "uniqueItems": true,
      "default": ["free", "kill", "mount", "ps", "service", "shutdown", "ssh", "top", "vim"],
      "examples": [["ssh", "vim"]]
    }
  },
  "additionalProperties": false,
  "examples": [
    { "invalid-commands": ["ssh", "vim"] },
    { "severity": "info", "invalid-commands": ["shutdown"] }
  ]
}
`),
	"https://schemas.tally.dev/rules/hadolint/dl3026.schema.json": []byte(`
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.tally.dev/rules/hadolint/dl3026.schema.json",
  "title": "hadolint/DL3026 rule config",
  "description": "Configuration options for the hadolint/DL3026 rule.",
  "type": "object",
  "properties": {
    "severity": { "$ref": "../rule-config.schema.json#/$defs/severity" },
    "fix": { "$ref": "../rule-config.schema.json#/$defs/fix" },
    "exclude": { "$ref": "../rule-config.schema.json#/$defs/exclude" },
    "trusted-registries": {
      "type": "array",
      "description": "Allowed registries for base images in FROM (empty disables the rule). Supports \"*\", \"*.suffix\" and \"prefix*\" patterns.",
      "items": {
        "type": "string",
        "minLength": 1
      },
      "uniqueItems": true,
      "default": [],
      "examples": [["docker.io", "gcr.io"]]
    }
  },
  "additionalProperties": false,
  "examples": [
    { "trusted-registries": ["docker.io"] },
    { "severity": "warning", "trusted-registries": ["*.gcr.io", "ghcr.io"] }
  ]
}
`),
	"https://schemas.tally.dev/rules/hadolint/index.schema.json": []byte(`
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.tally.dev/rules/hadolint/index.schema.json",
  "$comment": "Code generated by _tools/schema-gen. DO NOT EDIT.",
  "title": "hadolint/* rule namespace config",
  "description": "Schema for rules.hadolint configuration; keys are rule names within the hadolint namespace.",
  "type": "object",
  "properties": {
    "DL3001": {
      "$ref": "./dl3001.schema.json"
    },
    "DL3026": {
      "$ref": "./dl3026.schema.json"
    }
  },
  "additionalProperties": {
    "$ref": "../rule-config.schema.json#/$defs/genericRuleConfig"
  },
  "examples": [
    {
      "DL3026": {
        "severity": "warning"
      }
    }
  ]
}
`),
	"https://schemas.tally.dev/rules/rule-config.schema.json": []byte(`
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.tally.dev/rules/rule-config.schema.json",
  "title": "Common rule configuration",
  "description": "Shared schema definitions for per-rule configuration across namespaces (tally/*, hadolint/*, buildkit/*).",
  "$defs": {
    "severity": {
      "title": "Rule severity",
      "type": "string",
      "description": "Override the rule's default severity. Use \"off\" to disable the rule.",
      "enum": ["off", "error", "warning", "info", "style"],
      "examples": ["warning"]
    },
    "fix": {
      "title": "Rule fix mode",
      "type": "string",
      "description": "Control when auto-fixes are applied for this rule.",
      "enum": ["never", "explicit", "always", "unsafe-only"],
      "examples": ["explicit"]
    },
    "exclude": {
      "title": "Rule exclusions",
      "type": "object",
      "description": "Exclude this rule for specific file paths.",
      "properties": {
        "paths": {
          "type": "array",
          "description": "Glob patterns to exclude (e.g. \"test/**\").",
          "items": { "type": "string" },
          "examples": ["test/**"]
        }
      },
      "additionalProperties": false,
      "examples": [
        {
          "paths": ["test/**", "**/vendor/**"]
        }
      ]
    },
    "genericRuleConfig": {
      "title": "Generic rule configuration",
      "type": "object",
      "description": "Generic per-rule configuration used for rules without rule-specific options.",
      "properties": {
        "severity": { "$ref": "#/$defs/severity" },
        "fix": { "$ref": "#/$defs/fix" },
        "exclude": { "$ref": "#/$defs/exclude" }
      },
      "additionalProperties": false,
      "examples": [
        { "severity": "warning" },
        { "fix": "explicit", "exclude": { "paths": ["test/**"] } }
      ]
    }
  }
}
`),
	"https://schemas.tally.dev/rules/tally/consistent-indentation.schema.json": []byte(`
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.tally.dev/rules/tally/consistent-indentation.schema.json",
  "title": "tally/consistent-indentation rule config",
  "description": "Configuration options for the tally/consistent-indentation rule.",
  "type": "object",
  "properties": {
    "severity": { "$ref": "../rule-config.schema.json#/$defs/severity" },
    "fix": { "$ref": "../rule-config.schema.json#/$defs/fix" },
    "exclude": { "$ref": "../rule-config.schema.json#/$defs/exclude" }
  },
  "additionalProperties": false,
  "examples": [
    { "severity": "style" },
    { "severity": "off" }
  ]
}
`),
	"https://schemas.tally.dev/rules/tally/index.schema.json": []byte(`
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.tally.dev/rules/tally/index.schema.json",
  "$comment": "Code generated by _tools/schema-gen. DO NOT EDIT.",
  "title": "tally/* rule namespace config",
  "description": "Schema for rules.tally configuration; keys are rule names within the tally namespace.",
  "type": "object",
  "properties": {
    "consistent-indentation": {
      "$ref": "./consistent-indentation.schema.json"
    },
    "max-lines": {
      "$ref": "./max-lines.schema.json"
    },
    "newline-between-instructions": {
      "$ref": "./newline-between-instructions.schema.json"
    },
    "newline-per-chained-call": {
      "$ref": "./newline-per-chained-call.schema.json"
    },
    "no-trailing-spaces": {
      "$ref": "./no-trailing-spaces.schema.json"
    },
    "prefer-add-unpack": {
      "$ref": "./prefer-add-unpack.schema.json"
    },
    "prefer-copy-heredoc": {
      "$ref": "./prefer-copy-heredoc.schema.json"
    },
    "prefer-multi-stage-build": {
      "$ref": "./prefer-multi-stage-build.schema.json"
    },
    "prefer-run-heredoc": {
      "$ref": "./prefer-run-heredoc.schema.json"
    }
  },
  "additionalProperties": {
    "$ref": "../rule-config.schema.json#/$defs/genericRuleConfig"
  },
  "examples": [
    {
      "max-lines": {
        "severity": "warning"
      }
    }
  ]
}
`),
	"https://schemas.tally.dev/rules/tally/max-lines.schema.json": []byte(`
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.tally.dev/rules/tally/max-lines.schema.json",
  "title": "tally/max-lines rule config",
  "description": "Configuration options for the tally/max-lines rule.",
  "type": "object",
  "properties": {
    "severity": { "$ref": "../rule-config.schema.json#/$defs/severity" },
    "fix": { "$ref": "../rule-config.schema.json#/$defs/fix" },
    "exclude": { "$ref": "../rule-config.schema.json#/$defs/exclude" },
    "max": {
      "type": "integer",
      "minimum": 0,
      "default": 50,
      "description": "Maximum number of lines allowed (0 = disabled).",
      "examples": [100]
    },
    "skip-blank-lines": {
      "type": "boolean",
      "default": true,
      "description": "Exclude blank lines from the count.",
      "examples": [true]
    },
    "skip-comments": {
      "type": "boolean",
      "default": true,
      "description": "Exclude comment lines from the count.",
      "examples": [true]
    }
  },
  "additionalProperties": false,
  "examples": [
    { "max": 100 },
    { "severity": "warning", "max": 200, "skip-comments": false },
    { "exclude": { "paths": ["test/**"] }, "max": 120 }
  ]
}
`),
	"https://schemas.tally.dev/rules/tally/newline-between-instructions.schema.json": []byte(`
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.tally.dev/rules/tally/newline-between-instructions.schema.json",
  "title": "tally/newline-between-instructions rule config",
  "description": "Configuration options for the tally/newline-between-instructions rule.",
  "type": "object",
  "properties": {
    "severity": { "$ref": "../rule-config.schema.json#/$defs/severity" },
    "fix": { "$ref": "../rule-config.schema.json#/$defs/fix" },
    "exclude": { "$ref": "../rule-config.schema.json#/$defs/exclude" },
    "mode": {
      "type": "string",
      "enum": ["grouped", "always", "never"],
      "default": "grouped",
      "description": "Controls blank-line behavior between instructions.",
      "examples": ["grouped"]
    }
  },
  "additionalProperties": false,
  "examples": [
    { "mode": "grouped" },
    { "severity": "style", "mode": "always" }
  ]
}
`),
	"https://schemas.tally.dev/rules/tally/newline-per-chained-call.schema.json": []byte(`
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.tally.dev/rules/tally/newline-per-chained-call.schema.json",
  "title": "tally/newline-per-chained-call rule config",
  "description": "Configuration options for the tally/newline-per-chained-call rule.",
  "type": "object",
  "properties": {
    "severity": { "$ref": "../rule-config.schema.json#/$defs/severity" },
    "fix": { "$ref": "../rule-config.schema.json#/$defs/fix" },
    "exclude": { "$ref": "../rule-config.schema.json#/$defs/exclude" },
    "min-commands": {
      "type": "integer",
      "minimum": 2,
      "default": 2,
      "description": "Minimum number of chained commands required to trigger splitting.",
      "examples": [3]
    }
  },
  "additionalProperties": false,
  "examples": [
    { "min-commands": 2 },
    { "severity": "style", "min-commands": 4 }
  ]
}
`),
	"https://schemas.tally.dev/rules/tally/no-trailing-spaces.schema.json": []byte(`
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.tally.dev/rules/tally/no-trailing-spaces.schema.json",
  "title": "tally/no-trailing-spaces rule config",
  "description": "Configuration options for the tally/no-trailing-spaces rule.",
  "type": "object",
  "properties": {
    "severity": { "$ref": "../rule-config.schema.json#/$defs/severity" },
    "fix": { "$ref": "../rule-config.schema.json#/$defs/fix" },
    "exclude": { "$ref": "../rule-config.schema.json#/$defs/exclude" },
    "skip-blank-lines": {
      "type": "boolean",
      "default": false,
      "description": "Skip lines that consist entirely of whitespace.",
      "examples": [true]
    },
    "ignore-comments": {
      "type": "boolean",
      "default": false,
      "description": "Skip any line whose first non-whitespace character is # (Dockerfile comments and # lines in heredocs).",
      "examples": [true]
    }
  },
  "additionalProperties": false,
  "examples": [
    { "ignore-comments": true },
    { "severity": "style", "skip-blank-lines": true }
  ]
}
`),
	"https://schemas.tally.dev/rules/tally/prefer-add-unpack.schema.json": []byte(`
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.tally.dev/rules/tally/prefer-add-unpack.schema.json",
  "title": "tally/prefer-add-unpack rule config",
  "description": "Configuration options for the tally/prefer-add-unpack rule.",
  "type": "object",
  "properties": {
    "severity": { "$ref": "../rule-config.schema.json#/$defs/severity" },
    "fix": { "$ref": "../rule-config.schema.json#/$defs/fix" },
    "exclude": { "$ref": "../rule-config.schema.json#/$defs/exclude" },
    "enabled": {
      "type": "boolean",
      "default": true,
      "description": "Enable or disable this rule (independent of severity).",
      "examples": [true]
    }
  },
  "additionalProperties": false,
  "examples": [
    { "enabled": false },
    { "severity": "info", "enabled": true }
  ]
}
`),
	"https://schemas.tally.dev/rules/tally/prefer-copy-heredoc.schema.json": []byte(`
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.tally.dev/rules/tally/prefer-copy-heredoc.schema.json",
  "title": "tally/prefer-copy-heredoc rule config",
  "description": "Configuration options for the tally/prefer-copy-heredoc rule.",
  "type": "object",
  "properties": {
    "severity": { "$ref": "../rule-config.schema.json#/$defs/severity" },
    "fix": { "$ref": "../rule-config.schema.json#/$defs/fix" },
    "exclude": { "$ref": "../rule-config.schema.json#/$defs/exclude" },
    "check-single-run": {
      "type": "boolean",
      "default": true,
      "description": "Detect single RUN instructions that create files and suggest COPY heredoc.",
      "examples": [true]
    },
    "check-consecutive-runs": {
      "type": "boolean",
      "default": true,
      "description": "Detect sequences of consecutive RUN instructions that create/append to the same file.",
      "examples": [true]
    }
  },
  "additionalProperties": false,
  "examples": [
    { "check-single-run": true, "check-consecutive-runs": true },
    { "severity": "style", "check-single-run": false }
  ]
}
`),
	"https://schemas.tally.dev/rules/tally/prefer-multi-stage-build.schema.json": []byte(`
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.tally.dev/rules/tally/prefer-multi-stage-build.schema.json",
  "title": "tally/prefer-multi-stage-build rule config",
  "description": "Configuration options for the tally/prefer-multi-stage-build rule.",
  "type": "object",
  "properties": {
    "severity": { "$ref": "../rule-config.schema.json#/$defs/severity" },
    "fix": { "$ref": "../rule-config.schema.json#/$defs/fix" },
    "exclude": { "$ref": "../rule-config.schema.json#/$defs/exclude" },
    "min-score": {
      "type": "integer",
      "minimum": 1,
      "default": 4,
      "description": "Minimum heuristic score required to trigger the suggestion.",
      "examples": [4]
    }
  },
  "additionalProperties": false,
  "examples": [
    { "min-score": 4 },
    { "severity": "info", "min-score": 6 }
  ]
}
`),
	"https://schemas.tally.dev/rules/tally/prefer-run-heredoc.schema.json": []byte(`
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.tally.dev/rules/tally/prefer-run-heredoc.schema.json",
  "title": "tally/prefer-run-heredoc rule config",
  "description": "Configuration options for the tally/prefer-run-heredoc rule.",
  "type": "object",
  "properties": {
    "severity": { "$ref": "../rule-config.schema.json#/$defs/severity" },
    "fix": { "$ref": "../rule-config.schema.json#/$defs/fix" },
    "exclude": { "$ref": "../rule-config.schema.json#/$defs/exclude" },
    "min-commands": {
      "type": "integer",
      "minimum": 2,
      "default": 3,
      "description": "Minimum number of commands required to trigger heredoc conversion.",
      "examples": [3]
    },
    "check-consecutive-runs": {
      "type": "boolean",
      "default": true,
      "description": "Enable detection of multiple consecutive RUN instructions.",
      "examples": [true]
    },
    "check-chained-commands": {
      "type": "boolean",
      "default": true,
      "description": "Enable detection of chained commands within a single RUN (via &&).",
      "examples": [true]
    }
  },
  "additionalProperties": false,
  "examples": [
    { "min-commands": 3 },
    { "severity": "style", "min-commands": 4, "check-chained-commands": false }
  ]
}
`),
}
