# escape=`

# This file is auto-generated by PostSharp.Engineering.

FROM mcr.microsoft.com/windows/servercore:ltsc2025

# The initial shell is Windows PowerShell (use full path to avoid HCS issues)
SHELL ["C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe", "-Command"]

# Prepare environment
ENV PSExecutionPolicyPreference=Bypass
ENV POWERSHELL_UPDATECHECK=Off
ENV TEMP=C:\Temp
ENV TMP=C:\Temp
ENV RUNNING_IN_DOCKER=TRUE
# Add Windows PowerShell to PATH (pwsh added later by PowershellComponent)
ENV PATH="C:\Windows\System32\WindowsPowerShell\v1.0;${PATH}"

# Enable long path support
RUN Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
# Install Git
RUN Invoke-WebRequest -Uri https://github.com/git-for-windows/git/releases/download/v2.50.0.windows.1/PortableGit-2.50.0-64-bit.7z.exe -OutFile PortableGit.exe; `
    Start-Process -FilePath .\PortableGit.exe -ArgumentList '-o"C:\git"', '-y' -Wait; `
    Remove-Item PortableGit.exe

# Add git to PATH using ENV directive (persists across shell switches)
ENV PATH="C:\git\cmd;C:\git\bin;C:\git\usr\bin;${PATH}"

RUN git config --system core.longpaths true

# Set CLAUDE_CODE_GIT_BASH_PATH for Claude Code
ENV CLAUDE_CODE_GIT_BASH_PATH=C:\git\bin\bash.exe

# Install PowerShell 7
RUN Invoke-WebRequest -Uri https://github.com/PowerShell/PowerShell/releases/download/v7.5.2/PowerShell-7.5.2-win-x64.msi -OutFile PowerShell.msi; `
    $process = Start-Process msiexec.exe -Wait -PassThru -ArgumentList '/I PowerShell.msi /quiet'; `
    if ($process.ExitCode -ne 0) { exit $process.ExitCode }; `
    Remove-Item PowerShell.msi

ENV PATH="C:\Program Files\PowerShell\7;${PATH}"

# Install Azure CLI
RUN Invoke-WebRequest -Uri https://aka.ms/installazurecliwindowsx64 -OutFile AzureCLI.msi; `
    $process = Start-Process msiexec.exe -Wait -PassThru -ArgumentList '/I AzureCLI.msi /quiet'; `
    if ($process.ExitCode -ne 0) { exit $process.ExitCode }; `
    Remove-Item AzureCLI.msi

ENV PATH="C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin;${PATH}"

# Download .NET Installer
RUN Invoke-WebRequest -Uri https://dot.net/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1

# Add .NET to PATH using ENV directive (persists across shell switches)
ENV PATH="C:\Program Files\dotnet;${PATH}"

# Install .NET Sdk 8.0.414
RUN & .\dotnet-install.ps1 -Version 8.0.414 -InstallDir 'C:\Program Files\dotnet'
# Install .NET DotNetRuntime 9.0.9
RUN & .\dotnet-install.ps1 -Version 9.0.9 -Runtime dotnet -InstallDir 'C:\Program Files\dotnet'
# Install .NET Sdk 10.0.100
RUN & .\dotnet-install.ps1 -Version 10.0.100 -InstallDir 'C:\Program Files\dotnet'

# Install VS Build Tools
COPY VisualStudio.17.14.15.Release.chman /VisualStudio.17.14.15.Release.chman

RUN Invoke-WebRequest -Uri https://aka.ms/vs/17/release/vs_buildtools.exe -OutFile vs_buildtools.exe; `
    $process = Start-Process .\vs_buildtools.exe -NoNewWindow -Wait -PassThru `
        -ArgumentList "--quiet", "--wait", "--norestart", "--nocache", "--installPath", "C:\BuildTools", "--installChannelUri", "c:\VisualStudio.17.14.15.Release.chman", "--installCatalogUri", "https://download.visualstudio.microsoft.com/download/pr/eb5f7427-d28f-4e06-95cc-093f6c2070c8/3480d7a528bad877857c92843bb1e9ce8ebd48a2bffcee366a98a7343f4d32fb/VisualStudio.vsman", "--productId", "Microsoft.VisualStudio.Product.BuildTools", "--add", "Microsoft.Component.MSBuild", "--add", "Microsoft.NetCore.Component.SDK", "--add", "Microsoft.Net.Component.4.7.2.TargetingPack", "--add", "Microsoft.Net.Component.4.7.2.SDK", "--add", "Microsoft.Net.Component.4.8.TargetingPack", "--add", "Microsoft.Net.Component.4.8.SDK"; `
    if ($process.ExitCode -ne 0) { `
     Get-ChildItem "$env:TEMP\dd_*.log" -ErrorAction SilentlyContinue | ForEach-Object { `
        Write-Host "=== Contents of $($_.Name) ==="; `
        Get-Content $_.FullName; `
        Write-Host "=== End of $($_.Name) ===" `
        }; `
     exit $process.ExitCode; `
     }; `
    Remove-Item C:\\vs_buildtools.exe;

ENV VSINSTALLDIR=C:\BuildTools

RUN New-Item -ItemType Directory -Path 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages' -Force | Out-Null"; `
    New-Item -ItemType Directory -Path 'C:\Program Files\dotnet\sdk\NuGetFallbackFolder' -Force | Out-Null
# Epilogue
# Create docker-context directory for build scripts
RUN New-Item -ItemType Directory -Path c:\docker-context -Force | Out-Null

# Create directories for mountpoints
ARG MOUNTPOINTS

RUN if ($env:MOUNTPOINTS) { `
        $mounts = $env:MOUNTPOINTS -split ';'; `
        foreach ($dir in $mounts) { `
            if ($dir) { `
                Write-Host "Creating directory $dir`."; `
                New-Item -ItemType Directory -Path $dir -Force | Out-Null; `
            } `
        } `
    }

# Import environment variables
COPY ReadEnvironmentVariables.ps1 c:\docker-context\ReadEnvironmentVariables.ps1
COPY .g/env.g.json c:\docker-context\env.g.json

RUN c:\docker-context\ReadEnvironmentVariables.ps1 c:\docker-context\env.g.json

# Copy Init.g.ps1 placeholder (drive mappings handled inline in docker run)
COPY .g/Init.g.ps1 c:\docker-context\Init.g.ps1

# Configure .NET SDK
ENV DOTNET_NOLOGO=1
