FROM ubuntu:22.04@sha256:962f6cadeae0ea6284001009daa4cc9a8c37e75d1f5191cf0eb83fe565b63dd7

# DL3001: Should trigger - running top in container is useless
RUN top

# This is fine - installing ssh package
RUN apt-get install -y ssh
