authors        = ["Wharflab <https://tally.wharflab.com/>"]
description    = "Dockerfile linting, formatting, and code actions powered by Tally"
id             = "tally"
name           = "Tally"
repository     = "https://github.com/wharflab/tally"
schema_version = 1
version        = "0.1.0"

[grammars.dockerfile]
commit     = "971acdd908568b4531b0ba28a445bf0bb720aba5"
repository = "https://github.com/camdencheek/tree-sitter-dockerfile"

[language_servers.tally]
code_actions_kind = ["quickfix", "source.fixAll.tally"]
languages         = ["Dockerfile"]
name              = "Tally"

[language_servers.tally.language_ids]
"Dockerfile" = "dockerfile"
