// Package protocol contains generated LSP protocol types.
//
// This package is generated by tools/lspgen (adapted from
// microsoft/typescript-go's lsproto generator).
//
//go:generate bun run ../../../tools/lspgen/fetchModel.mts
//go:generate bun run ../../../tools/lspgen/generate.mts
package protocol
