FROM ubuntu:22.04@sha256:962f6cadeae0ea6284001009daa4cc9a8c37e75d1f5191cf0eb83fe565b63dd7
RUN echo 'server {}' > /etc/nginx.conf
RUN apt-get update
RUN apt-get install -y curl
RUN apt-get install -y git
