FROM alpine:3.20
LABEL org.opencontainers.image.title="demo"
LABEL "bad key"=value
LABEL Bad.Key=value
LABEL bad/key=value
LABEL com.docker.compose.project=demo
LABEL com.docker.image.source.entrypoint=Dockerfile
LABEL "$LABEL_PREFIX.name"=demo
