// Code generated by tsquery; DO NOT EDIT.

package queries

import gotreesitter "github.com/odvcencio/gotreesitter"

// CommandMatch is a typed match for pattern 0 (command).
type CommandMatch struct {
	CommandName     *gotreesitter.Node
	CommandElements *gotreesitter.Node
}

// PowerShellCommandsQuery holds the compiled query.
type PowerShellCommandsQuery struct {
	q *gotreesitter.Query
}

// NewPowerShellCommandsQuery compiles the query against the given language.
func NewPowerShellCommandsQuery(lang *gotreesitter.Language) (*PowerShellCommandsQuery, error) {
	q, err := gotreesitter.NewQuery(`(command
  command_name: (command_name) @command_name
  command_elements: (command_elements) @command_elements)
`, lang)
	if err != nil {
		return nil, err
	}
	return &PowerShellCommandsQuery{q: q}, nil
}

// PowerShellCommandsQueryCursor iterates over typed matches.
type PowerShellCommandsQueryCursor struct {
	cursor *gotreesitter.QueryCursor
	query  *gotreesitter.Query
}

// Exec returns a cursor that yields typed matches.
func (q *PowerShellCommandsQuery) Exec(node *gotreesitter.Node, lang *gotreesitter.Language, source []byte) *PowerShellCommandsQueryCursor {
	return &PowerShellCommandsQueryCursor{
		cursor: q.q.Exec(node, lang, source),
		query:  q.q,
	}
}

// Next returns the next typed match, or false when done.
func (c *PowerShellCommandsQueryCursor) Next() (CommandMatch, bool) {
	m, ok := c.cursor.NextMatch()
	if !ok {
		return CommandMatch{}, false
	}
	var result CommandMatch
	for _, cap := range m.Captures {
		switch cap.Name {
		case "command_name":
			result.CommandName = cap.Node
		case "command_elements":
			result.CommandElements = cap.Node
		}
	}
	return result, true
}
