// Code generated by tsquery; DO NOT EDIT.

package queries

import gotreesitter "github.com/odvcencio/gotreesitter"

// CommentMatch is a typed match for pattern 0 (comment).
type CommentMatch struct {
	Comment *gotreesitter.Node
}

// VariableMatch is a typed match for pattern 1 (variable).
type VariableMatch struct {
	Variable *gotreesitter.Node
}

// DecimalIntegerLiteralMatch is a typed match for pattern 2 (decimal_integer_literal).
type DecimalIntegerLiteralMatch struct {
	Number *gotreesitter.Node
}

// HexadecimalIntegerLiteralMatch is a typed match for pattern 3 (hexadecimal_integer_literal).
type HexadecimalIntegerLiteralMatch struct {
	Number *gotreesitter.Node
}

// RealLiteralMatch is a typed match for pattern 4 (real_literal).
type RealLiteralMatch struct {
	Number *gotreesitter.Node
}

// ComparisonOperatorMatch is a typed match for pattern 5 (comparison_operator).
type ComparisonOperatorMatch struct {
	Operator *gotreesitter.Node
}

// FileRedirectionOperatorMatch is a typed match for pattern 6 (file_redirection_operator).
type FileRedirectionOperatorMatch struct {
	Operator *gotreesitter.Node
}

// CommandParameterMatch is a typed match for pattern 7 (command_parameter).
type CommandParameterMatch struct {
	Parameter *gotreesitter.Node
}

// MemberNameMatch is a typed match for pattern 8 (member_name).
type MemberNameMatch struct {
	Property *gotreesitter.Node
}

// StringLiteralMatch is a typed match for pattern 9 (string_literal).
type StringLiteralMatch struct {
	String *gotreesitter.Node
}

// ExpandableStringLiteralMatch is a typed match for pattern 10 (expandable_string_literal).
type ExpandableStringLiteralMatch struct {
	String *gotreesitter.Node
}

// ExpandableHereStringLiteralMatch is a typed match for pattern 11 (expandable_here_string_literal).
type ExpandableHereStringLiteralMatch struct {
	String *gotreesitter.Node
}

// VerbatimStringCharactersMatch is a typed match for pattern 12 (verbatim_string_characters).
type VerbatimStringCharactersMatch struct {
	String *gotreesitter.Node
}

// VerbatimHereStringCharactersMatch is a typed match for pattern 13 (verbatim_here_string_characters).
type VerbatimHereStringCharactersMatch struct {
	String *gotreesitter.Node
}

// PowerShellSemanticQuery holds the compiled query.
type PowerShellSemanticQuery struct {
	q *gotreesitter.Query
}

// NewPowerShellSemanticQuery compiles the query against the given language.
func NewPowerShellSemanticQuery(lang *gotreesitter.Language) (*PowerShellSemanticQuery, error) {
	q, err := gotreesitter.NewQuery(`(comment) @comment
(variable) @variable
(decimal_integer_literal) @number
(hexadecimal_integer_literal) @number
(real_literal) @number
(comparison_operator) @operator
(file_redirection_operator) @operator
(command_parameter) @parameter
(member_name) @property
(string_literal) @string
(expandable_string_literal) @string
(expandable_here_string_literal) @string
(verbatim_string_characters) @string
(verbatim_here_string_characters) @string
`, lang)
	if err != nil {
		return nil, err
	}
	return &PowerShellSemanticQuery{q: q}, nil
}

// PowerShellSemanticQueryCursor iterates over typed matches.
type PowerShellSemanticQueryCursor struct {
	cursor *gotreesitter.QueryCursor
	query  *gotreesitter.Query
}

// Exec returns a cursor that yields typed matches.
func (q *PowerShellSemanticQuery) Exec(node *gotreesitter.Node, lang *gotreesitter.Language, source []byte) *PowerShellSemanticQueryCursor {
	return &PowerShellSemanticQueryCursor{
		cursor: q.q.Exec(node, lang, source),
		query:  q.q,
	}
}

// Next returns the pattern index and raw match. Use the pattern-specific
// methods to convert to typed structs.
func (c *PowerShellSemanticQueryCursor) Next() (gotreesitter.QueryMatch, bool) {
	return c.cursor.NextMatch()
}

// MatchPattern0 converts a raw match (pattern 0) into a CommentMatch.
func MatchPattern0(m gotreesitter.QueryMatch) CommentMatch {
	var result CommentMatch
	for _, cap := range m.Captures {
		switch cap.Name {
		case "comment":
			result.Comment = cap.Node
		}
	}
	return result
}

// MatchPattern1 converts a raw match (pattern 1) into a VariableMatch.
func MatchPattern1(m gotreesitter.QueryMatch) VariableMatch {
	var result VariableMatch
	for _, cap := range m.Captures {
		switch cap.Name {
		case "variable":
			result.Variable = cap.Node
		}
	}
	return result
}

// MatchPattern2 converts a raw match (pattern 2) into a DecimalIntegerLiteralMatch.
func MatchPattern2(m gotreesitter.QueryMatch) DecimalIntegerLiteralMatch {
	var result DecimalIntegerLiteralMatch
	for _, cap := range m.Captures {
		switch cap.Name {
		case "number":
			result.Number = cap.Node
		}
	}
	return result
}

// MatchPattern3 converts a raw match (pattern 3) into a HexadecimalIntegerLiteralMatch.
func MatchPattern3(m gotreesitter.QueryMatch) HexadecimalIntegerLiteralMatch {
	var result HexadecimalIntegerLiteralMatch
	for _, cap := range m.Captures {
		switch cap.Name {
		case "number":
			result.Number = cap.Node
		}
	}
	return result
}

// MatchPattern4 converts a raw match (pattern 4) into a RealLiteralMatch.
func MatchPattern4(m gotreesitter.QueryMatch) RealLiteralMatch {
	var result RealLiteralMatch
	for _, cap := range m.Captures {
		switch cap.Name {
		case "number":
			result.Number = cap.Node
		}
	}
	return result
}

// MatchPattern5 converts a raw match (pattern 5) into a ComparisonOperatorMatch.
func MatchPattern5(m gotreesitter.QueryMatch) ComparisonOperatorMatch {
	var result ComparisonOperatorMatch
	for _, cap := range m.Captures {
		switch cap.Name {
		case "operator":
			result.Operator = cap.Node
		}
	}
	return result
}

// MatchPattern6 converts a raw match (pattern 6) into a FileRedirectionOperatorMatch.
func MatchPattern6(m gotreesitter.QueryMatch) FileRedirectionOperatorMatch {
	var result FileRedirectionOperatorMatch
	for _, cap := range m.Captures {
		switch cap.Name {
		case "operator":
			result.Operator = cap.Node
		}
	}
	return result
}

// MatchPattern7 converts a raw match (pattern 7) into a CommandParameterMatch.
func MatchPattern7(m gotreesitter.QueryMatch) CommandParameterMatch {
	var result CommandParameterMatch
	for _, cap := range m.Captures {
		switch cap.Name {
		case "parameter":
			result.Parameter = cap.Node
		}
	}
	return result
}

// MatchPattern8 converts a raw match (pattern 8) into a MemberNameMatch.
func MatchPattern8(m gotreesitter.QueryMatch) MemberNameMatch {
	var result MemberNameMatch
	for _, cap := range m.Captures {
		switch cap.Name {
		case "property":
			result.Property = cap.Node
		}
	}
	return result
}

// MatchPattern9 converts a raw match (pattern 9) into a StringLiteralMatch.
func MatchPattern9(m gotreesitter.QueryMatch) StringLiteralMatch {
	var result StringLiteralMatch
	for _, cap := range m.Captures {
		switch cap.Name {
		case "string":
			result.String = cap.Node
		}
	}
	return result
}

// MatchPattern10 converts a raw match (pattern 10) into a ExpandableStringLiteralMatch.
func MatchPattern10(m gotreesitter.QueryMatch) ExpandableStringLiteralMatch {
	var result ExpandableStringLiteralMatch
	for _, cap := range m.Captures {
		switch cap.Name {
		case "string":
			result.String = cap.Node
		}
	}
	return result
}

// MatchPattern11 converts a raw match (pattern 11) into a ExpandableHereStringLiteralMatch.
func MatchPattern11(m gotreesitter.QueryMatch) ExpandableHereStringLiteralMatch {
	var result ExpandableHereStringLiteralMatch
	for _, cap := range m.Captures {
		switch cap.Name {
		case "string":
			result.String = cap.Node
		}
	}
	return result
}

// MatchPattern12 converts a raw match (pattern 12) into a VerbatimStringCharactersMatch.
func MatchPattern12(m gotreesitter.QueryMatch) VerbatimStringCharactersMatch {
	var result VerbatimStringCharactersMatch
	for _, cap := range m.Captures {
		switch cap.Name {
		case "string":
			result.String = cap.Node
		}
	}
	return result
}

// MatchPattern13 converts a raw match (pattern 13) into a VerbatimHereStringCharactersMatch.
func MatchPattern13(m gotreesitter.QueryMatch) VerbatimHereStringCharactersMatch {
	var result VerbatimHereStringCharactersMatch
	for _, cap := range m.Captures {
		switch cap.Name {
		case "string":
			result.String = cap.Node
		}
	}
	return result
}
