FROM ubuntu:22.04@sha256:962f6cadeae0ea6284001009daa4cc9a8c37e75d1f5191cf0eb83fe565b63dd7
RUN printf 'zend_extension=opcache\n[opcache]\nopcache.enable=1\nopcache.memory_consumption=128\n' > /etc/app/php.ini
